# Brain Teasers
for more brain teasers, please see: http://www.labri.fr/perso/nrougier/teaching/numpy.100/index.html

In [1]:
import numpy as np
np.set_printoptions(precision=2)

### What version of NumPy are you using?

In [2]:
print(np.__version__)

1.14.0


### Display array elements in reverse order

In [3]:
my_array = np.arange(10)

In [4]:
my_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Triple elements in array

In [5]:
my_array * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

### Create array with 20 zeros; every fifth element equals four

In [7]:
my_array = np.zeros(20)

In [9]:
my_array[::5] = 4
print(my_array)

[4. 0. 0. 0. 0. 4. 0. 0. 0. 0. 4. 0. 0. 0. 0. 4. 0. 0. 0. 0.]


### Transpose the rows and columns

In [10]:
np.transpose(my_array)

array([4., 0., 0., 0., 0., 4., 0., 0., 0., 0., 4., 0., 0., 0., 0., 4., 0.,
       0., 0., 0.])

### Create a 5x5 identity matrix with integer components

In [21]:
my_matrix = np.matrix(np.eye(5,5),dtype='int')
my_matrix

matrix([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

### Find the mean of a vector with 30 random elements.  Can you guess the approximate value for the mean?

In [33]:
my_vector = np.random.randn(30000)
print(my_vector)
print(np.mean(my_vector))
print(np.std(my_vector))

[ 0.23 -0.24 -0.22 ... -0.12  0.06  0.25]
-0.01885960816584389
0.9999873596519285


#### Repeat, and visually estimate the mean for the sum of the two means

In [29]:
my_vector = np.random.randn(30)
print(my_vector)

[ 0.22 -0.49  0.34  0.2  -0.24 -0.64  0.74  0.39 -0.67 -0.98 -1.92  0.15
  0.1  -0.68  1.55  1.03 -0.51  0.06 -0.17 -1.58 -0.55 -2.01  1.86  0.29
 -0.07 -0.54 -1.04 -0.23 -0.22 -0.8 ]


#### Repeat, and visually estimate the mean for the sum of the two means

### Create an 8x8 checker board with alternating zeros and ones

In [58]:
my_mat = np.ones((8,8),dtype=int)
my_mat[1::2,::2]=0
my_mat[::2,1::2]=0
my_mat

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

### Create a sorted vector that contain 'n' random numbers

In [60]:
n = 20
my_array = np.random.random(n)
np.sort(my_array)
my_array

array([0.77, 0.63, 0.32, 0.79, 0.5 , 0.18, 0.52, 0.54, 0.23, 0.49, 0.95,
       0.6 , 0.49, 0.5 , 0.74, 0.87, 0.77, 0.24, 0.37, 0.43])

### Without sorting, replace largest element in random array with the value 1234

In [75]:
np.set_printoptions(precision=2)
np.set_printoptions(suppress=True)
my_array[my_array.argmax()] = 1234
#my_array(my_array == np.max(my_array))=1234
print(my_array)

[   0.77    0.63    0.32    0.79    0.5     0.18    0.52    0.54    0.23
    0.49 1234.      0.6     0.49    0.5     0.74    0.87    0.77    0.24
    0.37    0.43]


### Given the following data type and data set; sort according to 'height'

source: http://docs.scipy.org/doc/numpy/reference/generated/numpy.sort.html

In [6]:
camelot_dtype = [('name', 'S10'), ('height', float), ('age', int)]
camelot_values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahad', 1.7, 38)]

In [76]:
np.sort(camelot_dtype['heigh'])

TypeError: list indices must be integers or slices, not str

### Make an array read-only (immutable)

### Print enumerated values from a 3x3 NumPy array